// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKmGvId90yuL4bZhh2WDqi6und4fQo7CM',
    appId: '1:369498954311:web:b0041a3f8efd34b259ef62',
    messagingSenderId: '369498954311',
    projectId: 'chat-15d57',
    authDomain: 'chat-15d57.firebaseapp.com',
    storageBucket: 'chat-15d57.appspot.com',
    measurementId: 'G-V7PX1RBC36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdJ3o4YwpTUyF4RqOxhbK1B1qv5GynaSE',
    appId: '1:369498954311:android:96527f7afa76552559ef62',
    messagingSenderId: '369498954311',
    projectId: 'chat-15d57',
    storageBucket: 'chat-15d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFRXaC1h5T4jt0Qg4vTxhcPgN1RjThCCQ',
    appId: '1:369498954311:ios:2da26fa64203b73059ef62',
    messagingSenderId: '369498954311',
    projectId: 'chat-15d57',
    storageBucket: 'chat-15d57.appspot.com',
    iosClientId: '369498954311-0cgr0bs9k8h2o0q5u2jq3h8vej86i2f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFRXaC1h5T4jt0Qg4vTxhcPgN1RjThCCQ',
    appId: '1:369498954311:ios:b6825788b07b4cf759ef62',
    messagingSenderId: '369498954311',
    projectId: 'chat-15d57',
    storageBucket: 'chat-15d57.appspot.com',
    iosClientId: '369498954311-rvdfebadk2mdrc04lnelv441fro2lhpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
